# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # - jupyter_contrib_nbextensions#==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  #- jupyterhub-singleuser>=3.0,<4.0
  - jupyterhub-singleuser
  # Set default python version to 3.10 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.10
  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # Add other packages here
  - xarray
  - numpy
  - xagg
  - pandas
  - geopandas >= 0.12.0
  - xesmf >= 0.7.1
  - scipy
  - cmocean
  - matplotlib
  - seaborn
  - cartopy
  - tqdm
  - zarr
  - intake
  - intake-esm
  - gcsfs
  - dask
  - nc-time-axis
  - nodejs
  - dask_labextension
  - graphviz # for dask.visualize
  - dask-gateway 
  - dask-gateway-server-local
